# Site settings
title: life.log
author: Joyce Kung
email: thejoycekung@gmail.com
description: ""
baseurl: "/blog"
url: "http://thejoycekung.github.io"
twitter_username: seeroflights
github_username:  thejoycekung
email_username:  thejoycekung@gmail.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["Gruntfile.js","README.md"]

plugins: [jekyll-paginate, jekyll-remote-theme]
theme: tale



permalink:      /:year-:month-:day/:title
