# Site settings
title: help
header-img: img/home-bg.jpg
email: thejoycekung@gmail.com
description: "Posts and Jokes. I think."
baseurl: "/blog"
url: "http://thejoycekung.github.io"
twitter_username: seeroflights
github_username:  thejoycekung
email_username:  thejoycekung@gmail.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
